backend:
  name: github
  repo: WHITEEEED/cashflowblog2 # замени на свой репозиторий
  branch: main
  base_url: https://decap-auth-proxy.lavrinenko-george.workers.dev

media_folder: "static/uploads"
public_folder: "/uploads"

collections:
  - name: "posts"
    label: "Posts"
    folder: "content/posts"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Body", name: "body", widget: "markdown" }
